=== merlin-s/dsa5-char-gen/DSA5CharacterCreator/data/xsd/conditiontypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="condition-types">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="condition-type" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="condition-type">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="args"/>
        <xs:element name="code" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="args">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="arg" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="arg">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== merlin-s/dsa5-char-gen/DSA5CharacterCreator/data/conditiontypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<condition-types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/conditiontypes.xsd">
  <condition-type id="traitStatusCheck">
    <args>
      <arg id="trait" type="Trait"/>
      <arg id="traitStatus" type="TraitStatusEnum"/>
      <arg id="relOp" type="RelOp"/>
    </args>
    <code><![CDATA[args.relOp.op(char.traitStatus[args.trait].value, args.traitStatus.value)]]></code>
  </condition-type>
  <condition-type id="traitLevelCheck">
    <args>
      <arg id="trait" type="Trait"/>
      <arg id="traitLevel" type="int"/>
      <arg id="relOp" type="RelOp"/>
    </args>
    <code><![CDATA[args.relOp.op(char.traitLevels[args.trait], args.traitLevel)]]></code>
  </condition-type>
</condition-types>
